# Generated by Django 4.2.2 on 2023-09-28 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_alter_card_subtask_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='first.list'),
        ),
        migrations.AlterField(
            model_name='card_attachments',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_att', to='first.card'),
        ),
        migrations.AlterField(
            model_name='card_description',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_desc', to='first.card'),
        ),
        migrations.AlterField(
            model_name='card_labels',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_labels', to='first.card'),
        ),
        migrations.AlterField(
            model_name='card_related_images',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_images', to='first.card'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='first.card'),
        ),
        migrations.AlterField(
            model_name='list',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='first.project'),
        ),
    ]
