# Generated by Django 4.2.6 on 2023-10-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_card_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_subtask',
            name='task_name',
            field=models.CharField(max_length=300),
        ),
    ]
