# Generated by Django 4.2.2 on 2023-09-24 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100, unique=True)),
                ('card_logo', models.ImageField(upload_to='card_logo/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('completion_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=125, unique=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('wiki', models.CharField(default='IMG PROJECT', max_length=150)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('project_logo', models.ImageField(upload_to='project_logo/')),
                ('project_members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=150, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=400)),
                ('comment_time', models.DateTimeField(auto_now=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.card')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card_Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=300, unique=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('assignees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.card')),
            ],
        ),
        migrations.CreateModel(
            name='Card_related_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='card_images/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.card')),
            ],
        ),
        migrations.CreateModel(
            name='Card_Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=50, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.card')),
            ],
        ),
        migrations.CreateModel(
            name='Card_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.card')),
            ],
        ),
        migrations.CreateModel(
            name='Card_attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.URLField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.list'),
        ),
    ]
