# Generated by Django 4.2.2 on 2023-10-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_project_creator_alter_card_lid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(default='Untitled', max_length=100, unique=True),
        ),
    ]
