# Generated by Django 4.2.6 on 2023-10-23 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_alter_card_subtask_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_subtask',
            name='assignees',
        ),
        migrations.AddField(
            model_name='card_subtask',
            name='assignees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Task_Done_By', to=settings.AUTH_USER_MODEL),
        ),
    ]
