# Generated by Django 4.2.6 on 2023-10-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_remove_card_subtask_assignees_card_subtask_assignees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
